spring.application.name=Stuffing
spring.datasource.url=jdbc:postgresql://localhost:5432/Stuffing
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Password reset (minutes)
password-reset.expiration-minutes=30

server.port=8086

# Mail
# - En PFE/dev: laisse app.mail.enabled=false => aucun envoi SMTP (on loggue seulement)
# - Pour activer l'envoi: mets app.mail.enabled=true + renseigne spring.mail.username/password
#je veux active l'envoi de mail
app.mail.enabled=true


app.mail.from=no-reply@stuffing.local

# SMTP (exemple Gmail)


# SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohamednegzaoui8@gmail.com
spring.mail.password=tbrm qzxz gdmd uggp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Debug SMTP (optionnel)
# logging.level.org.springframework.mail=DEBUG
# logging.level.com.sun.mail=DEBUG
